project:
  type: website
  output-dir: _site

website:
  title: "Rebecca Chang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: project.qmd
        text: Project

format:
  html:
    theme: cosmo
    toc: false
